# This is a basic workflow to help you get started with Actions

name: Installomator Checker

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          path: Auto-App-Test

      - uses: actions/checkout@v4
        with:
          repository: Allingtonbe/Installomator
          ref: Allington-Release
          path: Installomator

      - name: Run Installomator
        run: |
          echo Running Installomator
          $GITHUB_WORKSPACE/Installomator/Installomator.sh firefoxpkg NOTIFY=success DEBUG=0
          echo Done
