# This is a basic workflow to help you get started with Actions

name: Installomator Checker

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Installomator label to run'
        required: false
        default: 'firefoxpkg'
        
jobs:
  OneLabel:
    # Run one Installomator label
    runs-on: macos-latest
    if: github.event.inputs.label != 'AllLabels'
    steps:
      - uses: actions/checkout@v4
        with:
          path: Auto-App-Test

      - uses: actions/checkout@v4
        with:
          repository: Allingtonbe/Installomator
          ref: Allington-Release
          path: Installomator

      - name: Run Installomator
        run: |
          echo Running Installomator
          sudo $GITHUB_WORKSPACE/Installomator/Installomator.sh ${{ github.event.inputs.label }} NOTIFY=success DEBUG=0
          echo Done

      - name: Run Installomator Check
        run: |
          echo Running Installomator Check
          chmod +x $GITHUB_WORKSPACE/Auto-App-Test/AutoAppsTest.sh
          $GITHUB_WORKSPACE/Auto-App-Test/AutoAppsTest.sh ${{ github.event.inputs.label }}
          echo Done
          
  AllLabels:
    # Run all Installomator labels
    runs-on: macos-latest
    if: github.event.inputs.label == 'AllLabels'
    steps:
      - uses: actions/checkout@v4
        with:
          path: Auto-App-Test

      - uses: actions/checkout@v4
        with:
          repository: Allingtonbe/Installomator
          ref: Allington-Release
          path: Installomator

      - name: Run Installomator
        run: |
          echo Running Installomator
          sudo $GITHUB_WORKSPACE/Auto-App-Test/RunInstallomator.sh $GITHUB_WORKSPACE/Auto-App-Test $GITHUB_WORKSPACE/Installomator
          echo Done

      - name: Run Installomator Check
        run: |
          echo Running Installomator Check
          chmod +x $GITHUB_WORKSPACE/Auto-App-Test/AutoAppsTest.sh
          $GITHUB_WORKSPACE/Auto-App-Test/AutoAppsTest.sh
          echo Done
