name: Workflow test

on:
  workflow_dispatch:
        
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: Auto-App-Test

      - name: Test
        run: |
          echo Test
          cat ./Labels.txt
